from .ClientInputWindow import ClientInputWindow
from .TableInputWindow import TableInputWindow
from .PurchaseOrderInputWindow import PurchaseOrderInputWindow
from .SupplierInputWindow import SupplierInputWindow
from .ProductTypeInputWindow import ProductTypeInputWindow
